# Generated by Django 6.0.6 on 2026-06-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('summary', models.CharField(max_length=300, verbose_name='кртакое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='полное описание')),
                ('status', models.ForeignKey(default='new', on_delete=django.db.models.deletion.PROTECT, to='issues.status', verbose_name='статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.type', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'трекер задач',
                'db_table': 'Issue',
            },
        ),
    ]
