# Generated by Django 6.0.6 on 2026-06-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': ('трекер задач',), 'verbose_name_plural': 'трекер задачи'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='issues.status', verbose_name='статус'),
        ),
        migrations.AlterModelTable(
            name='issue',
            table=None,
        ),
    ]
