# Generated by Django 6.0.6 on 2026-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_options_alter_issue_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='old_type',
            field=models.ManyToManyField(to='issues.type', verbose_name='тип'),
        ),
    ]
