# Generated by Django 6.0.6 on 2026-06-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_remove_issue_type_issue_old_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues.type', verbose_name='типы'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='old_type',
        ),
        migrations.AddField(
            model_name='issue',
            name='old_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='issues.type', verbose_name='тип старый'),
        ),
    ]
