# Generated by Django 6.0.6 on 2026-06-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20260611_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='old_type',
        ),
    ]
