# Generated by Django 6.0.6 on 2026-06-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_remove_issue_old_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='types',
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='issues.type', verbose_name='тип'),
        ),
    ]
