# Generated by Django 6.0.6 on 2026-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_remove_issue_types_issue_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues.type', verbose_name='типы'),
        ),
    ]
