# Generated by Django 6.0.6 on 2026-06-13 16:13

import issues.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_remove_issue_type_issue_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[issues.models.validators.MinWordsValidators(5)], verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=300, validators=[issues.models.validators.NoUpperCaseValidator(1)], verbose_name='краткое описание'),
        ),
    ]
